/**
 * Sample Reality Quiz for Accountant Career
 */

export const accountantQuiz = {
  title: "A Day as an Accountant",
  description: "Navigate financial analysis, ethical dilemmas, and deadline pressure. See if you can manage numbers and trust.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "During an audit, you discover a significant financial discrepancy that could indicate fraud. What do you do?",
      options: [
        {
          text: "Document thoroughly and report through proper channels immediately",
          insight: "Professional integrity and legal compliance - essential for accounting careers",
          scores: {
            technical: 10,
            collaboration: 9,
            pressure: 9,
            independence: 9,
            creativity: 5,
            workLifeBalance: 5,
          },
        },
        {
          text: "Investigate further yourself before reporting",
          insight: "Some investigation is reasonable but delays in reporting can be problematic",
          scores: {
            technical: 8,
            independence: 8,
            pressure: 7,
            collaboration: 5,
            creativity: 6,
            workLifeBalance: 4,
          },
        },
        {
          text: "Mention it to the client first to give them chance to explain",
          insight: "Compromises independence - auditors report to stakeholders, not clients",
          scores: {
            collaboration: 4,
            technical: 3,
            independence: -5,
            pressure: 4,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel conflicted about the consequences of reporting",
          insight: "Natural feeling but accountants must prioritize professional duty over relationships",
          scores: {
            pressure: -4,
            collaboration: 5,
            technical: 5,
            independence: 3,
            creativity: 3,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Accountants are trusted gatekeepers of financial integrity. Ethical obligations require reporting irregularities through proper channels.",
      realityNote: "Accountants face ethical dilemmas regularly. Those who maintain integrity build careers; those who don't face legal consequences and career ruin.",
    },
    {
      id: "q2",
      scenario: "It's April - tax season crunch. You're working 70-hour weeks for the 4th consecutive week. How do you handle it?",
      options: [
        {
          text: "Push through - it's temporary and part of the profession",
          insight: "Realistic acceptance of seasonal demands but monitor for burnout",
          scores: {
            pressure: 9,
            technical: 8,
            independence: 8,
            collaboration: 6,
            creativity: 4,
            workLifeBalance: -3,
          },
        },
        {
          text: "Maintain quality while protecting some personal time",
          insight: "Sustainable approach that prevents burnout while meeting deadlines",
          scores: {
            pressure: 8,
            workLifeBalance: 7,
            technical: 8,
            collaboration: 7,
            independence: 7,
            creativity: 6,
          },
        },
        {
          text: "Struggle with the pace and consider if this career is right for you",
          insight: "Honest self-reflection - seasonal crunch isn't for everyone",
          scores: {
            pressure: 3,
            workLifeBalance: 3,
            technical: 5,
            collaboration: 5,
            independence: 5,
            creativity: 4,
          },
        },
        {
          text: "Work efficiently to minimize overtime while still delivering quality",
          insight: "Process optimization focus that serves you well long-term",
          scores: {
            technical: 9,
            creativity: 8,
            pressure: 8,
            workLifeBalance: 7,
            independence: 8,
            collaboration: 6,
          },
        },
      ],
      explanation: "Public accounting has intense seasonal demands. Sustainable careers require efficient work habits and acceptance of cyclical intensity.",
      realityNote: "Tax season accountants average 55-70 hours/week for 3 months. Industry and government roles offer more consistent schedules.",
    },
    {
      id: "q3",
      scenario: "A client asks you to use an aggressive tax strategy that's technically legal but ethically questionable. What do you do?",
      options: [
        {
          text: "Decline and explain your professional boundaries",
          insight: "Clear ethical stance that protects your reputation and license",
          scores: {
            independence: 10,
            technical: 9,
            collaboration: 6,
            pressure: 8,
            creativity: 5,
            workLifeBalance: 7,
          },
        },
        {
          text: "Implement it - if it's legal, it's their right",
          insight: "Technically correct but reputation risk and potential future liability",
          scores: {
            technical: 6,
            independence: 5,
            collaboration: 5,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Explain risks clearly and let client make informed decision",
          insight: "Consultative approach that respects client autonomy while protecting yourself",
          scores: {
            collaboration: 9,
            technical: 9,
            independence: 8,
            pressure: 8,
            creativity: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Research alternative strategies that achieve similar results ethically",
          insight: "Creative problem-solving that serves client needs within your comfort zone",
          scores: {
            creativity: 10,
            technical: 9,
            collaboration: 9,
            independence: 8,
            pressure: 7,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Accountants constantly navigate the line between legal and ethical. Building a reputation for integrity matters more than any single client.",
      realityNote: "Aggressive tax strategies are scrutinized increasingly. Accountants who maintain ethical standards build more sustainable client relationships.",
    },
    {
      id: "q4",
      scenario: "You find repetitive financial analysis work boring, but it needs to be done accurately. How do you approach it?",
      options: [
        {
          text: "Create systems and templates to make routine work more efficient",
          insight: "Process improvement mindset that reduces tedium while maintaining quality",
          scores: {
            creativity: 10,
            technical: 9,
            independence: 8,
            pressure: 7,
            collaboration: 6,
            workLifeBalance: 7,
          },
        },
        {
          text: "Push through it - not every task will be exciting",
          insight: "Professional acceptance but may lead to burnout without process improvement",
          scores: {
            pressure: 7,
            technical: 7,
            independence: 7,
            collaboration: 5,
            creativity: 3,
            workLifeBalance: 5,
          },
        },
        {
          text: "Rush through to get to more interesting work",
          insight: "Dangerous in accounting - errors in routine work have serious consequences",
          scores: {
            technical: -6,
            pressure: 4,
            independence: 5,
            creativity: 3,
            collaboration: 3,
            workLifeBalance: 5,
          },
        },
        {
          text: "Question whether accounting is the right fit",
          insight: "Honest reflection - accounting involves significant repetitive detail work",
          scores: {
            pressure: 4,
            creativity: 5,
            independence: 6,
            technical: 5,
            collaboration: 4,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Accounting requires precision in routine tasks. Successful accountants find ways to maintain accuracy while improving efficiency.",
      realityNote: "65% of accounting work is routine analysis. Those who automate and systematize advance faster than those who just endure it.",
    },
    {
      id: "q5",
      scenario: "You discover an error in a tax return you filed last month. The error is in the client's favor. What do you do?",
      options: [
        {
          text: "Inform client and file amended return promptly",
          insight: "Professional integrity that protects both client and your license",
          scores: {
            technical: 10,
            collaboration: 10,
            independence: 9,
            pressure: 8,
            creativity: 5,
            workLifeBalance: 5,
          },
        },
        {
          text: "Keep quiet - client benefited and no one will notice",
          insight: "Professional misconduct that risks license and legal consequences",
          scores: {
            technical: -8,
            collaboration: -6,
            independence: -5,
            pressure: 4,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Correct it in next year's return without mentioning the error",
          insight: "Still not proper disclosure - errors should be addressed directly",
          scores: {
            technical: 3,
            collaboration: 2,
            independence: 3,
            pressure: 5,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Review your processes to prevent similar errors",
          insight: "Good but incomplete - must also correct the current error",
          scores: {
            technical: 7,
            creativity: 7,
            independence: 7,
            collaboration: 5,
            pressure: 6,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Errors happen. How you handle them defines your professionalism. Prompt disclosure and correction protect everyone.",
      realityNote: "Tax preparers have legal obligation to correct known errors. Cover-ups lead to penalties, license revocation, and potential criminal charges.",
    },
    {
      id: "q6",
      scenario: "A long-term client is unhappy with your fees and threatens to leave for a cheaper accountant. What do you do?",
      options: [
        {
          text: "Explain your value and maintain your pricing",
          insight: "Confidence in your worth but risk losing client",
          scores: {
            independence: 9,
            technical: 8,
            collaboration: 6,
            pressure: 7,
            creativity: 5,
            workLifeBalance: 7,
          },
        },
        {
          text: "Reduce fees to keep the client",
          insight: "Short-term retention but devalues your services and profitability",
          scores: {
            collaboration: 5,
            pressure: 4,
            independence: -3,
            technical: 5,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Discuss scope to find ways to reduce fees without cutting value",
          insight: "Consultative approach that finds win-win solutions",
          scores: {
            collaboration: 10,
            creativity: 9,
            technical: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Let them leave - clients who only want cheap aren't ideal",
          insight: "Sometimes right but may be closing door prematurely",
          scores: {
            independence: 8,
            pressure: 6,
            workLifeBalance: 8,
            technical: 6,
            collaboration: 3,
            creativity: 4,
          },
        },
      ],
      explanation: "Client relationships require balancing value delivery with fair pricing. The best accountants demonstrate value rather than compete on price.",
      realityNote: "Clients who leave for cheaper services often return after problems. Demonstrating value through advisory services creates loyal relationships.",
    },
  ],
  scoringGuide: {
    technical: { min: -20, max: 65, weight: 0.25 },
    pressure: { min: -10, max: 55, weight: 0.20 },
    collaboration: { min: -15, max: 60, weight: 0.15 },
    creativity: { min: -5, max: 60, weight: 0.15 },
    independence: { min: -15, max: 60, weight: 0.20 },
    workLifeBalance: { min: -10, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Accountant Potential",
      message: "Your responses show strong alignment with accounting realities. You demonstrate ethical integrity, attention to detail, client service orientation, and ability to handle deadline pressure. You understand the trust-based nature of the profession.",
    },
    medium: {
      min: 50,
      title: "Accounting Possible With Development",
      message: "You have some accounting aptitudes but may find seasonal intensity, ethical dilemmas, or routine detail work challenging. Consider industry accounting which offers more predictable hours, or bookkeeping to test your fit.",
    },
    low: {
      min: 0,
      title: "Consider Different Financial Roles",
      message: "Your responses suggest accounting's blend of routine precision, ethical gatekeeping, and seasonal crunch may not suit you. Consider financial analysis, business consulting, or operations roles that use numerical skills differently.",
    },
  },
};
