/**
 * Sample Reality Quiz for Civil Engineer Career
 */

export const civilEngineerQuiz = {
  title: "A Day as a Civil Engineer",
  description: "Navigate safety concerns, budget pressures, and construction challenges. See if you can build infrastructure that lasts.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "During construction, you discover soil conditions are worse than surveys indicated. Proper foundation will cost 30% more and delay by 2 months. What do you do?",
      options: [
        {
          text: "Report immediately and recommend proper foundation despite cost",
          insight: "Safety-first engineering - you understand the consequences of cutting corners",
          scores: {
            technical: 10,
            collaboration: 9,
            pressure: 9,
            independence: 8,
            creativity: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Look for alternative designs that meet safety standards at lower cost",
          insight: "Creative problem-solving that addresses both safety and budget",
          scores: {
            creativity: 10,
            technical: 9,
            collaboration: 8,
            pressure: 8,
            independence: 8,
            workLifeBalance: 5,
          },
        },
        {
          text: "Proceed with original design - surveys are probably close enough",
          insight: "Dangerous assumption that can lead to structural failure and liability",
          scores: {
            technical: -8,
            collaboration: -5,
            pressure: 4,
            independence: 5,
            creativity: 2,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel stressed about delivering bad news to the client",
          insight: "Natural feeling but engineers must communicate problems clearly",
          scores: {
            pressure: -5,
            collaboration: 4,
            technical: 5,
            independence: 4,
            creativity: 3,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Civil engineers face constant tension between safety and cost. The best never compromise structural integrity but find creative solutions where possible.",
      realityNote: "Engineering failures cost billions annually and can cost lives. Professional engineers have legal and ethical obligations that override budget pressure.",
    },
    {
      id: "q2",
      scenario: "A contractor is not following your specifications on reinforcement spacing. They say their method is 'close enough' and faster. What do you do?",
      options: [
        {
          text: "Stop work immediately until they comply with specifications",
          insight: "Proper quality control - specifications exist for structural reasons",
          scores: {
            technical: 10,
            independence: 9,
            pressure: 8,
            collaboration: 6,
            creativity: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Document the deviation and let them continue",
          insight: "Abdication of engineering responsibility - you're liable for what gets built",
          scores: {
            technical: -5,
            collaboration: -3,
            pressure: 4,
            independence: -4,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Explain why the specification matters and offer to discuss alternatives",
          insight: "Educational approach that can improve contractor relationship and compliance",
          scores: {
            collaboration: 10,
            technical: 9,
            creativity: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Report to site supervisor and let them handle enforcement",
          insight: "Appropriate escalation but direct communication often resolves faster",
          scores: {
            collaboration: 6,
            pressure: 6,
            technical: 7,
            independence: 5,
            creativity: 4,
            workLifeBalance: 7,
          },
        },
      ],
      explanation: "Engineers must ensure contractors follow specifications. This requires both technical authority and communication skills.",
      realityNote: "60% of construction defects stem from not following specifications. Engineers who build contractor relationships see better compliance.",
    },
    {
      id: "q3",
      scenario: "Weather delays have put your project 3 weeks behind schedule. Client is threatening penalties. What do you do?",
      options: [
        {
          text: "Propose accelerated schedule with additional crews",
          insight: "Problem-solving approach that offers solutions alongside problems",
          scores: {
            creativity: 9,
            collaboration: 9,
            technical: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 4,
          },
        },
        {
          text: "Point out that weather delays are not your fault per contract",
          insight: "Legally correct but doesn't help the relationship or solve the problem",
          scores: {
            technical: 6,
            independence: 7,
            collaboration: 3,
            pressure: 5,
            creativity: 3,
            workLifeBalance: 7,
          },
        },
        {
          text: "Rush work to make up time",
          insight: "Rushing increases errors, accidents, and quality issues",
          scores: {
            technical: -4,
            collaboration: 4,
            pressure: 5,
            independence: 5,
            creativity: 3,
            workLifeBalance: 3,
          },
        },
        {
          text: "Resequence work activities to recover time without adding cost",
          insight: "Creative scheduling that demonstrates project management expertise",
          scores: {
            creativity: 10,
            technical: 9,
            collaboration: 8,
            pressure: 9,
            independence: 8,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Schedule pressure is constant in construction. Engineers must find ways to recover time without compromising safety or quality.",
      realityNote: "70% of construction projects experience significant delays. Schedule recovery skills are as important as technical skills.",
    },
    {
      id: "q4",
      scenario: "Your design would work better with premium materials, but client only approved budget materials. What do you do?",
      options: [
        {
          text: "Design with budget materials that meet code requirements",
          insight: "Professional approach - you work within constraints while meeting standards",
          scores: {
            technical: 9,
            collaboration: 8,
            creativity: 7,
            pressure: 7,
            independence: 7,
            workLifeBalance: 7,
          },
        },
        {
          text: "Insist on premium materials - it's the right engineering choice",
          insight: "May be technically better but overrides client decision-making",
          scores: {
            technical: 7,
            independence: 8,
            collaboration: 3,
            creativity: 4,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Present lifecycle cost analysis showing premium materials save money long-term",
          insight: "Consultative approach that helps client make informed decision",
          scores: {
            collaboration: 10,
            technical: 9,
            creativity: 9,
            pressure: 7,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Use premium materials and bill as budget materials",
          insight: "Fraud that can end your career and result in legal action",
          scores: {
            technical: -8,
            collaboration: -8,
            independence: -5,
            pressure: 3,
            creativity: 2,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Engineers often recommend solutions clients don't want to pay for. The best present value clearly and respect final client decisions.",
      realityNote: "Engineering is advisory - clients make final decisions within code requirements. Presenting information clearly is more effective than insisting.",
    },
    {
      id: "q5",
      scenario: "A project requires environmental mitigation that adds significant cost and time. You believe the requirements are excessive. What do you do?",
      options: [
        {
          text: "Comply fully while exploring ways to optimize approach",
          insight: "Professional approach that respects regulations while seeking efficiency",
          scores: {
            technical: 9,
            collaboration: 9,
            creativity: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Do minimum compliance - the rules are unreasonable",
          insight: "Risky approach that can lead to enforcement actions and project delays",
          scores: {
            technical: 4,
            collaboration: 3,
            independence: 6,
            pressure: 5,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Advocate for changing the regulations through proper channels",
          insight: "Appropriate long-term approach but doesn't solve current project needs",
          scores: {
            independence: 8,
            collaboration: 7,
            technical: 7,
            creativity: 6,
            pressure: 5,
            workLifeBalance: 5,
          },
        },
        {
          text: "Find innovative mitigation methods that exceed requirements at lower cost",
          insight: "Creative engineering that can turn constraints into opportunities",
          scores: {
            creativity: 10,
            technical: 10,
            collaboration: 8,
            pressure: 8,
            independence: 8,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Environmental requirements are increasing. Engineers who find creative compliance methods add significant value.",
      realityNote: "Sustainable engineering is growing field. Engineers with environmental expertise command premium rates as regulations increase.",
    },
    {
      id: "q6",
      scenario: "After project completion, you discover a minor design flaw that's not dangerous but will reduce structure lifespan by 10%. What do you do?",
      options: [
        {
          text: "Disclose to client and offer remediation options",
          insight: "Professional integrity - disclosure protects everyone long-term",
          scores: {
            technical: 10,
            collaboration: 10,
            independence: 9,
            creativity: 7,
            pressure: 8,
            workLifeBalance: 5,
          },
        },
        {
          text: "Keep quiet - it's not a safety issue and no one will know",
          insight: "Ethical violation that undermines professional responsibility",
          scores: {
            technical: -6,
            collaboration: -7,
            independence: -5,
            pressure: 4,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Monitor the structure and address if issues develop",
          insight: "Passive approach that may not catch problems before they worsen",
          scores: {
            technical: 5,
            collaboration: 4,
            independence: 5,
            pressure: 5,
            creativity: 4,
            workLifeBalance: 7,
          },
        },
        {
          text: "Document for your records but don't inform client",
          insight: "Protects you but not the client - incomplete ethical response",
          scores: {
            technical: 4,
            collaboration: -3,
            independence: 5,
            pressure: 5,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Engineers have ongoing responsibility for their designs. Disclosure of issues, even minor ones, is part of professional integrity.",
      realityNote: "Engineering professional codes require disclosure of issues that affect public welfare. Reputation for integrity is career-defining.",
    },
  ],
  scoringGuide: {
    technical: { min: -25, max: 65, weight: 0.25 },
    pressure: { min: -15, max: 55, weight: 0.20 },
    collaboration: { min: -25, max: 65, weight: 0.15 },
    creativity: { min: -5, max: 65, weight: 0.20 },
    independence: { min: -15, max: 55, weight: 0.15 },
    workLifeBalance: { min: -5, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Civil Engineer Potential",
      message: "Your responses show strong alignment with civil engineering realities. You demonstrate technical integrity, creative problem-solving under constraints, professional communication, and understanding of the balance between safety, cost, and schedule.",
    },
    medium: {
      min: 50,
      title: "Engineering Possible With Development",
      message: "You have some engineering aptitudes but may find the safety responsibility, budget pressure, or contractor management challenging. Consider starting in a design firm where you can develop these skills with more mentorship.",
    },
    low: {
      min: 0,
      title: "Consider Different Technical Roles",
      message: "Your responses suggest civil engineering's blend of safety responsibility, budget constraints, and field oversight may not suit you. Consider roles in technical consulting, construction management, or urban planning that use similar skills differently.",
    },
  },
};
