/**
 * Sample Reality Quiz for Data Scientist Career
 */

export const dataScientistQuiz = {
  title: "A Day as a Data Scientist",
  description: "Navigate complex analyses, stakeholder expectations, and ethical dilemmas. See if you can turn data into decisions.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "Stakeholders want you to prove their hypothesis is correct, but your analysis shows it's wrong. What do you do?",
      options: [
        {
          text: "Present findings honestly and recommend alternative approaches",
          insight: "Scientific integrity combined with solution-oriented thinking - ideal data scientist mindset",
          scores: {
            technical: 10,
            collaboration: 9,
            pressure: 8,
            creativity: 8,
            independence: 9,
            workLifeBalance: 5,
          },
        },
        {
          text: "Find a way to present data that supports their view",
          insight: "Compromising scientific integrity destroys long-term credibility",
          scores: {
            technical: -7,
            collaboration: 4,
            pressure: 5,
            independence: -5,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Ask for more time to find data that might support their hypothesis",
          insight: "Reasonable if genuinely uncertain but can become avoidance",
          scores: {
            technical: 6,
            collaboration: 6,
            pressure: 5,
            independence: 5,
            creativity: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel uncomfortable delivering findings that disappoint stakeholders",
          insight: "Common feeling but data scientists must be truth-tellers regardless of popularity",
          scores: {
            pressure: -5,
            collaboration: 5,
            technical: 6,
            independence: 3,
            creativity: 4,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Data scientists are trusted to provide unbiased analysis. Maintaining integrity while being diplomatically honest is essential.",
      realityNote: "68% of data scientists report pressure to present findings favorably. Those who maintain integrity build stronger long-term careers.",
    },
    {
      id: "q2",
      scenario: "Your model shows significant bias against a demographic group. Fixing it will delay launch by 2 months. What do you do?",
      options: [
        {
          text: "Flag the issue immediately and advocate for delay to fix it",
          insight: "Ethical leadership - you understand the real-world impact of biased models",
          scores: {
            technical: 10,
            collaboration: 9,
            independence: 9,
            creativity: 7,
            pressure: 8,
            workLifeBalance: 4,
          },
        },
        {
          text: "Launch anyway - business timelines are critical",
          insight: "Dangerous prioritization that can lead to serious harm and liability",
          scores: {
            technical: -6,
            collaboration: -4,
            pressure: 5,
            independence: 4,
            creativity: 2,
            workLifeBalance: 6,
          },
        },
        {
          text: "Document the bias and let leadership decide",
          insight: "Transfers responsibility but you remain accountable as the technical expert",
          scores: {
            technical: 6,
            collaboration: 6,
            independence: 5,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 7,
          },
        },
        {
          text: "Find a faster partial fix that reduces bias without full delay",
          insight: "Pragmatic problem-solving that balances ethics with business reality",
          scores: {
            creativity: 10,
            technical: 9,
            collaboration: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "ML ethics is a critical and growing concern. Data scientists must advocate for fairness while understanding business constraints.",
      realityNote: "62% of companies have deployed models with known bias issues. Data scientists who flag these issues early are increasingly valued.",
    },
    {
      id: "q3",
      scenario: "You have a tight deadline to deliver analysis. You can deliver something quick but surface-level, or thorough but late. What do you choose?",
      options: [
        {
          text: "Deliver thorough analysis late - quality matters more",
          insight: "Quality focus is good but missing deadlines repeatedly hurts credibility",
          scores: {
            technical: 9,
            independence: 8,
            creativity: 7,
            collaboration: 4,
            pressure: 4,
            workLifeBalance: 5,
          },
        },
        {
          text: "Deliver quick analysis on time with caveats about limitations",
          insight: "Pragmatic approach with transparency - shows you understand business reality",
          scores: {
            collaboration: 9,
            pressure: 9,
            technical: 7,
            creativity: 7,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Negotiate for more time while starting the work",
          insight: "Proactive communication about constraints - professional approach",
          scores: {
            collaboration: 10,
            pressure: 8,
            technical: 8,
            creativity: 7,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Work overtime to deliver thorough analysis on time",
          insight: "Dedication is valued but unsustainable and may not be necessary",
          scores: {
            technical: 8,
            pressure: 7,
            independence: 7,
            collaboration: 6,
            creativity: 6,
            workLifeBalance: -6,
          },
        },
      ],
      explanation: "Data scientists constantly balance thoroughness with timeliness. The best communicate tradeoffs clearly and set realistic expectations.",
      realityNote: "Average data scientist spends 45% of time on data cleaning. Time estimation is one of the hardest skills to master.",
    },
    {
      id: "q4",
      scenario: "Your carefully crafted insights are being ignored because non-technical stakeholders don't understand them. What do you do?",
      options: [
        {
          text: "Present findings more simply with visuals and stories",
          insight: "Communication is as important as technical skills - you adapt to your audience",
          scores: {
            collaboration: 10,
            creativity: 9,
            technical: 8,
            pressure: 7,
            independence: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Provide more technical detail so they understand the rigor",
          insight: "More detail often makes comprehension worse, not better",
          scores: {
            technical: 7,
            independence: 7,
            collaboration: 3,
            creativity: 4,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel frustrated that people don't value your analysis",
          insight: "Understandable but communication is your responsibility, not theirs",
          scores: {
            pressure: -4,
            collaboration: 3,
            technical: 5,
            creativity: 3,
            independence: 5,
            workLifeBalance: 4,
          },
        },
        {
          text: "Find a business champion who can translate for you",
          insight: "Smart strategy that leverages others' strengths while building relationships",
          scores: {
            collaboration: 9,
            creativity: 8,
            technical: 7,
            pressure: 7,
            independence: 5,
            workLifeBalance: 7,
          },
        },
      ],
      explanation: "The best insights are worthless if not communicated effectively. Data scientists must translate complexity into actionable stories.",
      realityNote: "Data scientists with strong communication skills earn 30% more than those with only technical skills. Storytelling is essential.",
    },
    {
      id: "q5",
      scenario: "A quick heuristic would solve the problem well enough, but you want to build an elegant ML model. What do you choose?",
      options: [
        {
          text: "Build the elegant ML model - this is what data science is about",
          insight: "Overengineering is a common trap that wastes resources",
          scores: {
            technical: 6,
            creativity: 6,
            independence: 7,
            collaboration: 3,
            pressure: 4,
            workLifeBalance: 4,
          },
        },
        {
          text: "Start with heuristic, add ML only if it meaningfully improves results",
          insight: "Pragmatic approach that prioritizes business value over technical elegance",
          scores: {
            technical: 9,
            collaboration: 9,
            creativity: 8,
            pressure: 8,
            independence: 8,
            workLifeBalance: 7,
          },
        },
        {
          text: "Build both and compare performance",
          insight: "Thorough but may not be worth the time investment",
          scores: {
            technical: 8,
            creativity: 7,
            independence: 7,
            collaboration: 6,
            pressure: 5,
            workLifeBalance: 4,
          },
        },
        {
          text: "Ask stakeholders which approach they prefer",
          insight: "Good for buy-in but they may not have the technical context to decide",
          scores: {
            collaboration: 7,
            technical: 6,
            independence: 4,
            creativity: 5,
            pressure: 6,
            workLifeBalance: 7,
          },
        },
      ],
      explanation: "Mature data scientists know that simple solutions often outperform complex ones. Business impact matters more than technical sophistication.",
      realityNote: "Research shows 87% of data science projects never reach production. Starting simple dramatically increases deployment success.",
    },
    {
      id: "q6",
      scenario: "You've spent 3 months on a project and realize your approach won't work. What do you do?",
      options: [
        {
          text: "Pivot immediately and communicate learnings to stakeholders",
          insight: "Scientific mindset - failure is information, not defeat",
          scores: {
            technical: 10,
            collaboration: 10,
            creativity: 9,
            pressure: 8,
            independence: 8,
            workLifeBalance: 5,
          },
        },
        {
          text: "Keep trying - maybe with more data or tuning it will work",
          insight: "Persistence can become sunk cost fallacy",
          scores: {
            technical: 5,
            independence: 6,
            creativity: 4,
            collaboration: 3,
            pressure: 4,
            workLifeBalance: 3,
          },
        },
        {
          text: "Feel like a failure for wasting 3 months",
          insight: "Natural feeling but research involves dead ends - this is normal",
          scores: {
            pressure: -6,
            collaboration: 4,
            technical: 5,
            creativity: 3,
            independence: 4,
            workLifeBalance: 2,
          },
        },
        {
          text: "Document why it didn't work for future reference",
          insight: "Valuable but should be combined with pivot and communication",
          scores: {
            technical: 7,
            independence: 7,
            collaboration: 5,
            creativity: 5,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Data science involves experimentation and failure. The best scientists fail fast, learn quickly, and communicate openly.",
      realityNote: "60% of data science experiments don't produce actionable results. How you handle 'failed' projects defines your career growth.",
    },
  ],
  scoringGuide: {
    technical: { min: -20, max: 65, weight: 0.25 },
    pressure: { min: -20, max: 55, weight: 0.15 },
    collaboration: { min: -10, max: 65, weight: 0.20 },
    creativity: { min: -5, max: 60, weight: 0.20 },
    independence: { min: -10, max: 55, weight: 0.15 },
    workLifeBalance: { min: -15, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Data Scientist Potential",
      message: "Your responses show strong alignment with data science realities. You demonstrate scientific integrity, pragmatic problem-solving, communication skills, and comfort with ambiguity and failure. You understand that business impact matters more than technical elegance.",
    },
    medium: {
      min: 50,
      title: "Data Science Possible With Development",
      message: "You have some data science aptitudes but may find stakeholder management, communication challenges, or ethical dilemmas difficult. Consider starting as a data analyst or ML engineer to develop these skills in a more structured environment.",
    },
    low: {
      min: 0,
      title: "Consider Different Technical Roles",
      message: "Your responses suggest data science's blend of technical depth, stakeholder communication, and ethical decision-making may not suit you. Consider software engineering, data engineering, or research roles that focus more on technical execution.",
    },
  },
};
