/**
 * Sample Reality Quiz for Graphic Designer Career
 */

export const graphicDesignerQuiz = {
  title: "A Day as a Graphic Designer",
  description: "Navigate client feedback, creative constraints, and tight deadlines. See if you can balance artistry with business needs.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "A client hates the design you're proud of and want major changes. Their suggestions would make it worse in your professional opinion. What do you do?",
      options: [
        {
          text: "Push back firmly - you're the expert, they hired you for your vision",
          insight: "Standing ground can work but risks damaging client relationship",
          scores: {
            creativity: 8,
            independence: 9,
            collaboration: 3,
            pressure: 6,
            technical: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Ask questions to understand their concerns, then propose compromise solutions",
          insight: "Collaborative problem-solving that respects both expertise and client needs",
          scores: {
            collaboration: 10,
            creativity: 9,
            technical: 9,
            pressure: 8,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Make all their changes - client is always right",
          insight: "Avoids conflict but may result in poor portfolio work and burnout",
          scores: {
            collaboration: 5,
            independence: -4,
            creativity: -3,
            pressure: 5,
            technical: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel hurt that they don't appreciate your work",
          insight: "Natural reaction but design is service work - feedback isn't personal rejection",
          scores: {
            pressure: -5,
            creativity: 4,
            collaboration: 3,
            independence: 4,
            technical: 4,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Designers must separate ego from work while still advocating for good design. Finding middle ground through dialogue is key.",
      realityNote: "Designers report client feedback as their #1 challenge. Those who learn to negotiate collaboratively have longer, happier careers.",
    },
    {
      id: "q2",
      scenario: "You're asked to design for a brand with strict guidelines that severely limit creativity. How do you approach it?",
      options: [
        {
          text: "Find creative solutions within the constraints",
          insight: "Professional mindset - constraints can spark innovation",
          scores: {
            creativity: 10,
            technical: 9,
            collaboration: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel frustrated by the limitations",
          insight: "Understandable but most design work involves significant constraints",
          scores: {
            creativity: 3,
            pressure: -4,
            independence: 5,
            collaboration: 4,
            technical: 5,
            workLifeBalance: 4,
          },
        },
        {
          text: "Ignore some guidelines to make better design",
          insight: "Breaking brand guidelines damages client trust and your reputation",
          scores: {
            creativity: 5,
            independence: 7,
            collaboration: -5,
            technical: 3,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Suggest guideline updates that would improve design flexibility",
          insight: "Strategic approach that adds value beyond immediate project",
          scores: {
            collaboration: 9,
            creativity: 8,
            technical: 8,
            independence: 8,
            pressure: 7,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Most design work happens within brand constraints. Great designers find creative solutions without breaking established systems.",
      realityNote: "90% of professional design work involves existing brand guidelines. Thriving within constraints is a core professional skill.",
    },
    {
      id: "q3",
      scenario: "Client asks for 'one more round of revisions' for the 5th time, well beyond scope. What do you do?",
      options: [
        {
          text: "Do the revisions to keep client happy",
          insight: "Accommodating but sets precedent for scope creep that hurts your business",
          scores: {
            collaboration: 5,
            independence: -4,
            pressure: 4,
            technical: 5,
            creativity: 4,
            workLifeBalance: -5,
          },
        },
        {
          text: "Explain scope limits and offer revisions for additional fee",
          insight: "Professional boundary-setting that respects both parties",
          scores: {
            independence: 10,
            collaboration: 8,
            pressure: 8,
            technical: 8,
            creativity: 6,
            workLifeBalance: 8,
          },
        },
        {
          text: "Get frustrated and rush through revisions",
          insight: "Damages relationship and quality - lose-lose outcome",
          scores: {
            pressure: -5,
            collaboration: -3,
            creativity: 2,
            independence: 5,
            technical: 3,
            workLifeBalance: 3,
          },
        },
        {
          text: "Try to understand why they're not satisfied to prevent future rounds",
          insight: "Root cause analysis can prevent endless revisions",
          scores: {
            collaboration: 9,
            technical: 8,
            creativity: 7,
            pressure: 7,
            independence: 7,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Scope management is critical for sustainable design careers. Setting clear boundaries professionally protects your time and sanity.",
      realityNote: "Freelance designers lose average 20% of income to unbilled revisions. Contract clarity and boundary-setting are survival skills.",
    },
    {
      id: "q4",
      scenario: "Your computer crashes and you lose a day's work on a project due tomorrow. What do you do?",
      options: [
        {
          text: "Panic and feel overwhelmed by the situation",
          insight: "Natural reaction but design deadlines require quick recovery",
          scores: {
            pressure: -7,
            creativity: 3,
            collaboration: 4,
            independence: 3,
            technical: 4,
            workLifeBalance: 2,
          },
        },
        {
          text: "Pull an all-nighter to redo everything",
          insight: "Dedication but unsustainable and may not be necessary",
          scores: {
            pressure: 7,
            independence: 8,
            technical: 7,
            creativity: 5,
            collaboration: 4,
            workLifeBalance: -8,
          },
        },
        {
          text: "Contact client immediately to negotiate extension",
          insight: "Transparent communication often earns goodwill and flexibility",
          scores: {
            collaboration: 10,
            pressure: 8,
            independence: 7,
            technical: 7,
            creativity: 6,
            workLifeBalance: 7,
          },
        },
        {
          text: "Recreate work efficiently using shortcuts since you've already solved the problem",
          insight: "Practical approach - second version is often faster and better",
          scores: {
            creativity: 9,
            pressure: 9,
            technical: 9,
            independence: 8,
            collaboration: 6,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Technical failures happen. Designers need backup systems and the ability to recover quickly under pressure.",
      realityNote: "72% of designers have lost significant work to technical failures. Automated backups and version control are professional necessities.",
    },
    {
      id: "q5",
      scenario: "A fellow designer copies your portfolio piece closely for their own client work. How do you respond?",
      options: [
        {
          text: "Confront them directly and demand they take it down",
          insight: "Direct approach may be warranted but consider relationship impact",
          scores: {
            independence: 9,
            pressure: 7,
            collaboration: 3,
            creativity: 5,
            technical: 6,
            workLifeBalance: 6,
          },
        },
        {
          text: "Let it go - imitation is flattery",
          insight: "Passive approach that may enable continued copying",
          scores: {
            collaboration: 5,
            pressure: 5,
            independence: 3,
            creativity: 4,
            technical: 4,
            workLifeBalance: 8,
          },
        },
        {
          text: "Document the issue and reach out professionally to discuss",
          insight: "Measured approach that protects your work while maintaining professionalism",
          scores: {
            collaboration: 8,
            independence: 8,
            pressure: 8,
            technical: 8,
            creativity: 6,
            workLifeBalance: 6,
          },
        },
        {
          text: "Focus on continuing to create original work that can't be easily copied",
          insight: "Forward-thinking approach but doesn't address the immediate issue",
          scores: {
            creativity: 9,
            independence: 8,
            pressure: 7,
            technical: 7,
            collaboration: 5,
            workLifeBalance: 7,
          },
        },
      ],
      explanation: "Design copying is unfortunately common. Handling it professionally while protecting your work is an important skill.",
      realityNote: "45% of designers report having work copied. Building a distinctive style and documenting your process provides some protection.",
    },
    {
      id: "q6",
      scenario: "You've been doing the same type of work for 2 years and feel creatively stagnant. What do you do?",
      options: [
        {
          text: "Keep doing what pays while pursuing personal projects on the side",
          insight: "Balanced approach that maintains income while feeding creativity",
          scores: {
            creativity: 8,
            workLifeBalance: 6,
            independence: 8,
            technical: 7,
            collaboration: 5,
            pressure: 6,
          },
        },
        {
          text: "Actively pursue different types of clients and projects",
          insight: "Proactive career management that drives growth",
          scores: {
            creativity: 10,
            independence: 9,
            collaboration: 8,
            technical: 8,
            pressure: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Accept that professional design isn't always exciting",
          insight: "Realistic but may lead to burnout if creative needs aren't met",
          scores: {
            pressure: 5,
            workLifeBalance: 7,
            creativity: 2,
            independence: 5,
            technical: 6,
            collaboration: 5,
          },
        },
        {
          text: "Consider leaving design for something more fulfilling",
          insight: "May be valid but explore options within design first",
          scores: {
            creativity: 4,
            independence: 6,
            pressure: 3,
            technical: 4,
            collaboration: 4,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Creative burnout is real. Successful designers actively manage their career to maintain both income and creative fulfillment.",
      realityNote: "Design career satisfaction drops significantly after year 3 without variety. Active portfolio diversification is essential.",
    },
  ],
  scoringGuide: {
    technical: { min: -5, max: 60, weight: 0.15 },
    pressure: { min: -25, max: 55, weight: 0.20 },
    collaboration: { min: -15, max: 65, weight: 0.15 },
    creativity: { min: -10, max: 65, weight: 0.30 },
    independence: { min: -10, max: 60, weight: 0.15 },
    workLifeBalance: { min: -20, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Graphic Designer Potential",
      message: "Your responses show strong alignment with graphic design realities. You demonstrate creative problem-solving, client management skills, professional boundary-setting, and resilience under pressure. You understand design is both art and service.",
    },
    medium: {
      min: 50,
      title: "Design Career Possible With Development",
      message: "You have creative aptitude but may find client feedback, scope management, or creative constraints challenging. Consider starting in-house where you'll have more stability while developing these professional skills.",
    },
    low: {
      min: 0,
      title: "Consider Different Creative Paths",
      message: "Your responses suggest professional design's blend of client service, tight deadlines, and creative constraints may not suit you. Consider fine art, art direction (more concept, less execution), or UX research where you can use creativity differently.",
    },
  },
};
