/**
 * Sample Reality Quiz for Lawyer Career
 */

export const lawyerQuiz = {
  title: "A Day as a Lawyer",
  description: "Navigate ethical boundaries, client demands, and courtroom pressure. See if you can advocate effectively while upholding justice.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "Your client tells you they're guilty but wants to plead not guilty. What do you do?",
      options: [
        {
          text: "Defend them vigorously - everyone deserves representation",
          insight: "Understanding of constitutional duty - defense lawyers protect process not guilt",
          scores: {
            technical: 10,
            pressure: 9,
            independence: 9,
            collaboration: 7,
            creativity: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Refuse to take the case",
          insight: "May feel right but undermines principle that everyone deserves defense",
          scores: {
            independence: 7,
            technical: 5,
            collaboration: 3,
            pressure: 5,
            creativity: 3,
            workLifeBalance: 7,
          },
        },
        {
          text: "Encourage them to plead guilty",
          insight: "May be good advice but must respect client's ultimate decision",
          scores: {
            collaboration: 6,
            technical: 7,
            independence: 6,
            pressure: 6,
            creativity: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel conflicted about defending someone you know is guilty",
          insight: "Normal feeling but defense lawyers must separate personal morality from professional duty",
          scores: {
            pressure: -5,
            independence: 4,
            technical: 5,
            collaboration: 5,
            creativity: 4,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Criminal defense is about protecting constitutional rights, not personal morality. Lawyers must separate their role from personal judgment.",
      realityNote: "Every defendant deserves vigorous representation - it's how the adversarial system protects everyone's rights, including the innocent.",
    },
    {
      id: "q2",
      scenario: "Opposing counsel is using aggressive, borderline unethical tactics in court. What do you do?",
      options: [
        {
          text: "Match their aggression - fight fire with fire",
          insight: "Risks your reputation and may violate professional conduct rules",
          scores: {
            pressure: 6,
            independence: 6,
            technical: 4,
            collaboration: -4,
            creativity: 4,
            workLifeBalance: 5,
          },
        },
        {
          text: "Stay professional and object when appropriate",
          insight: "Maintains integrity while protecting client - sustainable approach",
          scores: {
            technical: 10,
            collaboration: 8,
            pressure: 9,
            independence: 9,
            creativity: 6,
            workLifeBalance: 6,
          },
        },
        {
          text: "Report them to the bar association",
          insight: "Appropriate for serious violations but may be premature",
          scores: {
            technical: 7,
            independence: 8,
            collaboration: 4,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel intimidated by their aggressive approach",
          insight: "Natural feeling but courtroom advocacy requires composure under pressure",
          scores: {
            pressure: -6,
            collaboration: 4,
            technical: 4,
            independence: 3,
            creativity: 3,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Legal practice involves adversarial situations. The best lawyers maintain professionalism while effectively advocating for clients.",
      realityNote: "Judges and juries notice unprofessional behavior. Long-term reputation is built on integrity, not aggressive tactics.",
    },
    {
      id: "q3",
      scenario: "You're in the middle of a major case when your child has a school emergency. What do you do?",
      options: [
        {
          text: "Handle the work emergency first - the case is critical",
          insight: "May be necessary sometimes but patterns like this lead to family problems",
          scores: {
            pressure: 7,
            technical: 7,
            independence: 7,
            collaboration: 4,
            creativity: 4,
            workLifeBalance: -7,
          },
        },
        {
          text: "Ask colleague to cover while you handle family emergency",
          insight: "Professional approach that uses team resources appropriately",
          scores: {
            collaboration: 10,
            workLifeBalance: 9,
            pressure: 8,
            technical: 7,
            independence: 5,
            creativity: 6,
          },
        },
        {
          text: "Try to handle both simultaneously",
          insight: "Neither gets full attention - risky for both priorities",
          scores: {
            pressure: 5,
            technical: 4,
            collaboration: 5,
            independence: 6,
            creativity: 5,
            workLifeBalance: 3,
          },
        },
        {
          text: "Feel guilty no matter which choice you make",
          insight: "Common lawyer experience - work-life conflict is a major career challenge",
          scores: {
            pressure: -4,
            workLifeBalance: -3,
            collaboration: 5,
            technical: 5,
            independence: 4,
            creativity: 4,
          },
        },
      ],
      explanation: "Law is demanding and often conflicts with personal life. Successful lawyers build support systems and set boundaries.",
      realityNote: "Lawyers report highest work-family conflict of any profession. Those who build collaborative practices have better long-term outcomes.",
    },
    {
      id: "q4",
      scenario: "A client asks you to pursue a legal strategy you believe is technically valid but morally wrong. What do you do?",
      options: [
        {
          text: "Pursue it - your job is to represent their interests within the law",
          insight: "Technically correct but may conflict with your values over time",
          scores: {
            technical: 7,
            independence: 5,
            collaboration: 6,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 5,
          },
        },
        {
          text: "Explain your concerns and suggest alternative approaches",
          insight: "Counselor role that serves client while maintaining your integrity",
          scores: {
            collaboration: 10,
            technical: 9,
            independence: 9,
            creativity: 9,
            pressure: 8,
            workLifeBalance: 6,
          },
        },
        {
          text: "Refuse and let them find another lawyer",
          insight: "Protects your values but may abandon client inappropriately",
          scores: {
            independence: 8,
            workLifeBalance: 7,
            technical: 5,
            collaboration: 3,
            pressure: 5,
            creativity: 3,
          },
        },
        {
          text: "Feel torn between duty to client and personal ethics",
          insight: "Common dilemma - lawyers must develop framework for these decisions",
          scores: {
            pressure: -3,
            independence: 5,
            technical: 5,
            collaboration: 5,
            creativity: 4,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Lawyers are counselors, not just technicians. The best advise clients on broader implications while respecting their autonomy.",
      realityNote: "Lawyers who maintain clear ethical boundaries report higher career satisfaction. 'Technical compliance' without ethics leads to burnout.",
    },
    {
      id: "q5",
      scenario: "A client with limited resources needs representation in a case you normally wouldn't take. What do you do?",
      options: [
        {
          text: "Take it pro bono - access to justice matters",
          insight: "Professional obligation and personal fulfillment from public service",
          scores: {
            collaboration: 10,
            independence: 8,
            technical: 8,
            creativity: 7,
            pressure: 7,
            workLifeBalance: 4,
          },
        },
        {
          text: "Refer to legal aid - that's what they're for",
          insight: "Appropriate referral but may not solve client's problem",
          scores: {
            collaboration: 6,
            technical: 6,
            independence: 6,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 8,
          },
        },
        {
          text: "Decline - you can't solve everyone's problems",
          insight: "Sometimes necessary but consider pro bono obligations",
          scores: {
            independence: 7,
            workLifeBalance: 8,
            technical: 5,
            collaboration: 3,
            pressure: 6,
            creativity: 3,
          },
        },
        {
          text: "Offer reduced fee arrangement",
          insight: "Creative approach that balances service with sustainability",
          scores: {
            creativity: 9,
            collaboration: 9,
            technical: 8,
            independence: 7,
            pressure: 7,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Lawyers have professional obligation to ensure access to justice. Finding balance between service and sustainability is important.",
      realityNote: "Most bar associations require pro bono hours. Lawyers who do meaningful pro bono report higher job satisfaction.",
    },
    {
      id: "q6",
      scenario: "You lose a case you were confident about winning. Your client is devastated. How do you respond?",
      options: [
        {
          text: "Explain options for appeal and next steps professionally",
          insight: "Professional response that maintains client relationship and explores remedies",
          scores: {
            technical: 9,
            collaboration: 9,
            pressure: 8,
            independence: 8,
            creativity: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Take it personally and question your abilities",
          insight: "Understandable but lawyers lose cases - resilience is essential",
          scores: {
            pressure: -6,
            workLifeBalance: -4,
            collaboration: 5,
            technical: 5,
            independence: 4,
            creativity: 3,
          },
        },
        {
          text: "Blame external factors - judge was biased, jury was wrong",
          insight: "Deflecting responsibility damages credibility and misses learning",
          scores: {
            collaboration: -3,
            technical: 3,
            independence: 5,
            pressure: 4,
            creativity: 2,
            workLifeBalance: 6,
          },
        },
        {
          text: "Analyze what went wrong to improve for future cases",
          insight: "Growth mindset that turns losses into learning opportunities",
          scores: {
            technical: 10,
            creativity: 8,
            independence: 9,
            collaboration: 7,
            pressure: 8,
            workLifeBalance: 5,
          },
        },
      ],
      explanation: "Even excellent lawyers lose cases. How you handle losses - professionally and with learning orientation - defines career longevity.",
      realityNote: "Trial lawyers lose 30-50% of cases on average. Resilience and continuous improvement are more important than winning streaks.",
    },
  ],
  scoringGuide: {
    technical: { min: -5, max: 65, weight: 0.20 },
    pressure: { min: -25, max: 55, weight: 0.25 },
    collaboration: { min: -10, max: 65, weight: 0.15 },
    creativity: { min: -5, max: 55, weight: 0.15 },
    independence: { min: -5, max: 60, weight: 0.20 },
    workLifeBalance: { min: -20, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Lawyer Potential",
      message: "Your responses show strong alignment with legal practice realities. You demonstrate ethical judgment, advocacy skills, resilience under pressure, and understanding of the balance between client service and professional obligations.",
    },
    medium: {
      min: 50,
      title: "Legal Career Possible With Development",
      message: "You have some aptitudes for law but may find the ethical dilemmas, adversarial nature, or work-life demands challenging. Consider law school clinics and internships to test fit before committing to the profession.",
    },
    low: {
      min: 0,
      title: "Consider Different Advocacy Roles",
      message: "Your responses suggest legal practice's blend of adversarial advocacy, ethical complexity, and intense pressure may not suit you. Consider mediation, compliance, policy research, or paralegal work that uses similar skills differently.",
    },
  },
};
