/**
 * Sample Reality Quiz for Marketing Manager Career
 */

export const marketingManagerQuiz = {
  title: "A Day as a Marketing Manager",
  description: "Navigate campaigns, budgets, and stakeholder expectations. See if you can drive results under pressure.",
  duration: 6,
  questions: [
    {
      id: "q1",
      scenario: "Your biggest campaign just launched and initial metrics show it's underperforming. The CEO wants answers in tomorrow's meeting. What do you do?",
      options: [
        {
          text: "Wait for more data before drawing conclusions",
          insight: "Patience is wise but leadership expects proactive communication during high-stakes campaigns",
          scores: {
            technical: 7,
            pressure: 5,
            collaboration: 4,
            creativity: 5,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Analyze data overnight, identify issues, and present solutions alongside problems",
          insight: "Solution-oriented leadership - you understand executives want answers not just data",
          scores: {
            technical: 10,
            pressure: 9,
            collaboration: 8,
            creativity: 9,
            independence: 8,
            workLifeBalance: -3,
          },
        },
        {
          text: "Blame the underperformance on external factors beyond your control",
          insight: "Deflecting responsibility damages credibility and misses learning opportunities",
          scores: {
            technical: 3,
            pressure: 4,
            collaboration: -4,
            creativity: 2,
            independence: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel anxious about presenting bad news to leadership",
          insight: "Natural feeling but marketing requires delivering uncomfortable truths with confidence",
          scores: {
            pressure: -6,
            collaboration: 4,
            technical: 5,
            creativity: 3,
            independence: 3,
            workLifeBalance: 2,
          },
        },
      ],
      explanation: "Marketing managers face constant performance scrutiny. The best prepare solutions alongside problems and communicate proactively.",
      realityNote: "67% of marketing campaigns underperform initial expectations. How you respond to setbacks defines your career trajectory.",
    },
    {
      id: "q2",
      scenario: "You have budget for only one initiative: a safe campaign with predictable ROI or an innovative campaign that could be huge or flop. What do you choose?",
      options: [
        {
          text: "Take the safe option - predictable results protect your job",
          insight: "Risk-averse approach may limit career growth but provides stability",
          scores: {
            creativity: 3,
            pressure: 6,
            technical: 7,
            collaboration: 5,
            independence: 6,
            workLifeBalance: 7,
          },
        },
        {
          text: "Go innovative - breakthrough results require bold moves",
          insight: "High risk tolerance can lead to big wins or career setbacks",
          scores: {
            creativity: 10,
            pressure: 7,
            independence: 9,
            technical: 6,
            collaboration: 5,
            workLifeBalance: 4,
          },
        },
        {
          text: "Split budget to test innovation while maintaining baseline results",
          insight: "Balanced approach shows strategic thinking and risk management",
          scores: {
            creativity: 8,
            technical: 9,
            collaboration: 7,
            pressure: 8,
            independence: 7,
            workLifeBalance: 6,
          },
        },
        {
          text: "Research competitor strategies before deciding",
          insight: "Data-informed decisions are smart but sometimes you must lead not follow",
          scores: {
            technical: 8,
            creativity: 6,
            collaboration: 6,
            independence: 6,
            pressure: 6,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Marketing requires balancing creativity with accountability. The best marketers find ways to innovate while managing risk.",
      realityNote: "CMOs who take calculated creative risks are 3x more likely to be promoted than those who only run safe campaigns.",
    },
    {
      id: "q3",
      scenario: "Your data shows the CEO's favorite marketing channel is actually your worst performer. How do you handle this?",
      options: [
        {
          text: "Present the data objectively and recommend reallocation",
          insight: "Courage to speak truth to power with data - essential for senior marketing roles",
          scores: {
            technical: 10,
            collaboration: 8,
            pressure: 9,
            independence: 9,
            creativity: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Keep funding the channel to avoid conflict",
          insight: "Avoiding difficult conversations wastes resources and undermines your expertise",
          scores: {
            collaboration: 3,
            pressure: 4,
            technical: 3,
            independence: -3,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Slowly reduce budget over time without direct confrontation",
          insight: "Avoids conflict but lacks transparency that builds trust",
          scores: {
            collaboration: 4,
            technical: 6,
            pressure: 5,
            independence: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Find ways to make the CEO's preferred channel work better first",
          insight: "Diplomatic approach that explores all options before recommending changes",
          scores: {
            collaboration: 9,
            creativity: 8,
            technical: 8,
            pressure: 7,
            independence: 6,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Marketing managers must navigate politics while staying data-driven. The best find diplomatic ways to deliver difficult truths.",
      realityNote: "73% of marketing decisions are influenced by executive preferences. Success requires balancing data with organizational dynamics.",
    },
    {
      id: "q4",
      scenario: "A social media crisis erupts Saturday morning - a customer complaint goes viral and is damaging your brand. What do you do?",
      options: [
        {
          text: "Wait until Monday to craft a proper response with legal review",
          insight: "Too slow - social media crises escalate hourly, not daily",
          scores: {
            pressure: 3,
            collaboration: 4,
            technical: 5,
            creativity: 3,
            independence: 5,
            workLifeBalance: 8,
          },
        },
        {
          text: "Respond immediately with empathy, take conversation offline, and mobilize team",
          insight: "Crisis management instincts - speed and empathy are critical",
          scores: {
            pressure: 10,
            collaboration: 9,
            creativity: 8,
            technical: 9,
            independence: 7,
            workLifeBalance: -5,
          },
        },
        {
          text: "Delete negative comments to contain the spread",
          insight: "Dangerous approach that typically amplifies backlash",
          scores: {
            technical: -5,
            collaboration: -6,
            pressure: 4,
            creativity: 2,
            independence: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Feel stressed about ruined weekend but recognize it comes with the job",
          insight: "Realistic understanding but crisis response is time-sensitive",
          scores: {
            pressure: 5,
            workLifeBalance: 3,
            collaboration: 5,
            technical: 5,
            creativity: 4,
            independence: 5,
          },
        },
      ],
      explanation: "Social media crises don't respect business hours. Marketing managers must be ready to respond quickly and strategically anytime.",
      realityNote: "Brands that respond to social media crises within 1 hour see 25% less reputation damage than those that wait 24 hours.",
    },
    {
      id: "q5",
      scenario: "Your creative team presents a campaign concept you think is mediocre. They're excited about it. What do you do?",
      options: [
        {
          text: "Approve it to keep team morale high",
          insight: "Short-term harmony but long-term quality and credibility suffer",
          scores: {
            collaboration: 5,
            pressure: 4,
            creativity: -3,
            technical: 3,
            independence: 3,
            workLifeBalance: 7,
          },
        },
        {
          text: "Reject it and provide specific feedback on what needs improvement",
          insight: "Direct feedback drives quality but delivery matters for team relationships",
          scores: {
            technical: 8,
            creativity: 7,
            independence: 9,
            pressure: 7,
            collaboration: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Ask probing questions to help them see the weaknesses themselves",
          insight: "Coaching approach builds team capability while improving output",
          scores: {
            collaboration: 10,
            creativity: 9,
            technical: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Take over and redo the concept yourself",
          insight: "Gets results but undermines team development and creates bottlenecks",
          scores: {
            creativity: 7,
            independence: 8,
            technical: 7,
            collaboration: -4,
            pressure: 6,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Marketing managers must maintain quality standards while developing their teams. The best use feedback as coaching opportunities.",
      realityNote: "Marketing managers spend 40% of time on people management. Technical marketing skills alone don't make successful leaders.",
    },
    {
      id: "q6",
      scenario: "Sales team blames your marketing for poor lead quality. You believe the leads are fine but sales isn't following up properly. How do you respond?",
      options: [
        {
          text: "Defend your team and show data proving lead quality",
          insight: "Defensive stance may be accurate but doesn't solve the business problem",
          scores: {
            technical: 7,
            independence: 7,
            collaboration: 3,
            pressure: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Propose joint analysis of the lead-to-close funnel to find real issues",
          insight: "Collaborative problem-solving that addresses root cause not blame",
          scores: {
            collaboration: 10,
            technical: 9,
            creativity: 8,
            pressure: 8,
            independence: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Accept blame to maintain relationship with sales",
          insight: "Avoids conflict but sets precedent for marketing being scapegoat",
          scores: {
            collaboration: 4,
            pressure: 3,
            independence: -4,
            technical: 3,
            creativity: 2,
            workLifeBalance: 5,
          },
        },
        {
          text: "Escalate to leadership to resolve the dispute",
          insight: "Sometimes necessary but try peer resolution first",
          scores: {
            pressure: 6,
            collaboration: 4,
            independence: 5,
            technical: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Marketing-Sales alignment is critical and often contentious. The best marketers build bridges through data and shared goals.",
      realityNote: "Companies with strong marketing-sales alignment see 38% higher win rates. This relationship is a career-defining skill.",
    },
  ],
  scoringGuide: {
    technical: { min: -10, max: 65, weight: 0.20 },
    pressure: { min: -15, max: 60, weight: 0.20 },
    collaboration: { min: -20, max: 65, weight: 0.20 },
    creativity: { min: -10, max: 60, weight: 0.25 },
    independence: { min: -10, max: 55, weight: 0.10 },
    workLifeBalance: { min: -10, max: 50, weight: 0.05 },
  },
  results: {
    high: {
      min: 70,
      title: "Strong Marketing Manager Potential",
      message: "Your responses show strong alignment with marketing management realities. You demonstrate data-driven thinking, creative problem-solving, stakeholder management skills, and comfort with ambiguity and pressure. You understand the blend of creativity and accountability the role requires.",
    },
    medium: {
      min: 50,
      title: "Marketing Role Possible With Development",
      message: "You have some marketing aptitudes but may find the constant pressure, political navigation, or 24/7 nature of crisis management challenging. Consider starting in a specialist role (content, social, analytics) before moving to management.",
    },
    low: {
      min: 0,
      title: "Consider Different Creative or Analytical Roles",
      message: "Your responses suggest marketing management's blend of creativity, data analysis, and high-pressure stakeholder management may not suit you. Consider roles in design, research, or project management that leverage your strengths with less cross-functional complexity.",
    },
  },
};
