/**
 * Sample Reality Quiz for Nurse/Healthcare Worker Career
 */

export const nurseQuiz = {
  title: "A Day as a Nurse",
  description: "Experience the intensity, compassion, and challenges of nursing. See if healthcare is your path.",
  duration: 7,
  questions: [
    {
      id: "q1",
      scenario: "You're caring for 6 patients when a 7th critical patient arrives. You're already behind on medication rounds. What do you do?",
      options: [
        {
          text: "Prioritize the critical patient immediately, delegate others to colleagues",
          insight: "You understand triage and teamwork - essential in high-pressure healthcare",
          scores: {
            pressure: 10,
            collaboration: 9,
            technical: 9,
            creativity: 6,
            independence: 5,
            workLifeBalance: -3,
          },
        },
        {
          text: "Finish current medication round first, then address new patient",
          insight: "Sticking to routine in emergencies can endanger patients - flexibility is crucial",
          scores: {
            pressure: 3,
            technical: 5,
            collaboration: 4,
            independence: 6,
            creativity: 2,
            workLifeBalance: 5,
          },
        },
        {
          text: "Call for backup immediately while starting triage assessment",
          insight: "You recognize limits and ask for help - smart resource management",
          scores: {
            collaboration: 10,
            pressure: 9,
            technical: 8,
            creativity: 7,
            independence: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel overwhelmed by impossible patient ratios",
          insight: "Valid feeling but nursing requires functioning under sustained pressure",
          scores: {
            pressure: -8,
            collaboration: 3,
            technical: 4,
            independence: 3,
            creativity: 2,
            workLifeBalance: -5,
          },
        },
      ],
      explanation: "Nurses constantly juggle competing priorities. The ability to triage, delegate, and ask for help saves lives.",
      realityNote: "82% of nurses report being regularly understaffed. Learning to work safely under pressure is critical.",
    },
    {
      id: "q2",
      scenario: "A patient is rude and verbally abusive to you despite your best care. How do you respond?",
      options: [
        {
          text: "Take it personally and feel hurt by their treatment",
          insight: "Understandable but unsustainable - you'll face this regularly in healthcare",
          scores: {
            pressure: -6,
            collaboration: 3,
            technical: 4,
            creativity: 2,
            independence: 3,
            workLifeBalance: -4,
          },
        },
        {
          text: "Recognize they're in pain/fear, maintain professionalism and compassion",
          insight: "Emotional maturity and empathy - hallmark of excellent nursing",
          scores: {
            collaboration: 10,
            pressure: 9,
            technical: 8,
            creativity: 6,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Set firm boundaries while continuing to provide quality care",
          insight: "You balance compassion with self-protection - both are necessary",
          scores: {
            pressure: 8,
            collaboration: 8,
            independence: 8,
            technical: 8,
            creativity: 6,
            workLifeBalance: 7,
          },
        },
        {
          text: "Avoid the patient and minimize interactions with them",
          insight: "Avoidance compromises patient care and doesn't resolve the issue",
          scores: {
            collaboration: -4,
            pressure: 3,
            technical: 2,
            independence: 6,
            creativity: 2,
            workLifeBalance: 6,
          },
        },
      ],
      explanation: "Difficult patients are part of nursing. The best nurses separate personal feelings from professional care while protecting their boundaries.",
      realityNote: "68% of nurses experience verbal abuse weekly. Developing emotional resilience is crucial for career longevity.",
    },
    {
      id: "q3",
      scenario: "You witness a doctor make what you believe is a medication error. What do you do?",
      options: [
        {
          text: "Question it respectfully and double-check the order before administering",
          insight: "Patient safety advocate - you understand nurses are last line of defense",
          scores: {
            collaboration: 9,
            pressure: 9,
            technical: 10,
            independence: 8,
            creativity: 6,
            workLifeBalance: 5,
          },
        },
        {
          text: "Administer it anyway - doctor knows best",
          insight: "Dangerous assumption - nurses prevent errors by questioning when needed",
          scores: {
            collaboration: 3,
            pressure: 5,
            technical: -5,
            independence: -3,
            creativity: 2,
            workLifeBalance: 6,
          },
        },
        {
          text: "Report to charge nurse and let them handle the confrontation",
          insight: "Appropriate escalation but direct communication often resolves issues faster",
          scores: {
            collaboration: 7,
            pressure: 6,
            technical: 7,
            independence: 4,
            creativity: 5,
            workLifeBalance: 7,
          },
        },
        {
          text: "Worry about challenging authority but ultimately stay silent",
          insight: "Fear of hierarchy can compromise patient safety - advocacy is essential",
          scores: {
            pressure: -5,
            collaboration: -3,
            technical: 3,
            independence: -4,
            creativity: 2,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Nurses catch medication errors daily. Speaking up diplomatically when something seems wrong is both professional duty and patient protection.",
      realityNote: "Nurses prevent an estimated 86% of medication errors before they reach patients. Questioning orders when appropriate is expected.",
    },
    {
      id: "q4",
      scenario: "Your 12-hour shift ends in 10 minutes but your replacement calls in sick. What do you do?",
      options: [
        {
          text: "Stay until replacement arrives, even if it means missing plans",
          insight: "Dedication to patients but this pace without boundaries leads to burnout",
          scores: {
            collaboration: 7,
            pressure: 7,
            technical: 7,
            independence: 6,
            workLifeBalance: -7,
            creativity: 4,
          },
        },
        {
          text: "Work with charge nurse to ensure safe handoff then leave",
          insight: "You balance patient safety with self-care - sustainable nursing practice",
          scores: {
            collaboration: 9,
            pressure: 8,
            technical: 8,
            workLifeBalance: 7,
            independence: 7,
            creativity: 6,
          },
        },
        {
          text: "Leave exactly on time - not my problem",
          insight: "While technically correct, rigid boundaries can harm patients in true emergencies",
          scores: {
            independence: 8,
            workLifeBalance: 8,
            collaboration: -5,
            pressure: 5,
            technical: 5,
            creativity: 4,
          },
        },
        {
          text: "Feel guilty and resentful about impossible expectations",
          insight: "Understandable but nursing requires navigating this tension constantly",
          scores: {
            pressure: -5,
            workLifeBalance: -4,
            collaboration: 4,
            technical: 5,
            independence: 4,
            creativity: 3,
          },
        },
      ],
      explanation: "Staffing issues are chronic in nursing. The key is ensuring patient safety while maintaining boundaries that prevent burnout.",
      realityNote: "Average nurse works 2-3 hours unpaid overtime weekly. Learning when to stay and when to advocate for staffing is crucial.",
    },
    {
      id: "q5",
      scenario: "A patient's family insists on a treatment you know is medically inappropriate. How do you handle it?",
      options: [
        {
          text: "Educate them gently about why it won't help and what will work",
          insight: "Patient/family education is core nursing - you do it with empathy",
          scores: {
            collaboration: 10,
            technical: 9,
            pressure: 8,
            creativity: 7,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Tell them firmly that's not how it works",
          insight: "Direct but may damage trust needed for therapeutic relationship",
          scores: {
            independence: 7,
            technical: 7,
            collaboration: 3,
            pressure: 6,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Page doctor to deal with family's expectations",
          insight: "Sometimes appropriate but nurses often handle these conversations effectively",
          scores: {
            collaboration: 6,
            technical: 6,
            independence: 3,
            pressure: 5,
            creativity: 4,
            workLifeBalance: 7,
          },
        },
        {
          text: "Feel caught between family wishes and medical facts",
          insight: "Common feeling but nurses navigate this tension constantly - communication is key",
          scores: {
            pressure: -3,
            collaboration: 5,
            technical: 5,
            independence: 4,
            creativity: 4,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Nurses bridge medical knowledge and patient/family understanding. The best do this with compassion while maintaining evidence-based practice.",
      realityNote: "Nurses spend 40% of patient interaction time on education and emotional support, not just medical tasks.",
    },
    {
      id: "q6",
      scenario: "You make a mistake that could have harmed a patient, but didn't. What do you do?",
      options: [
        {
          text: "Report it immediately through proper channels and learn from it",
          insight: "Professional integrity and growth mindset - this is how healthcare improves",
          scores: {
            collaboration: 10,
            technical: 10,
            pressure: 8,
            independence: 8,
            creativity: 6,
            workLifeBalance: 6,
          },
        },
        {
          text: "Keep quiet since no harm was done",
          insight: "Dangerous approach - near-misses are learning opportunities for entire team",
          scores: {
            collaboration: -7,
            technical: -5,
            pressure: 3,
            independence: 5,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Tell supervisor privately but don't formally document it",
          insight: "Partial accountability - formal reporting helps identify systemic issues",
          scores: {
            collaboration: 5,
            technical: 4,
            pressure: 6,
            independence: 6,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel intense guilt and anxiety about the mistake",
          insight: "Normal reaction but need healthy ways to process errors without paralysis",
          scores: {
            pressure: -6,
            collaboration: 5,
            technical: 5,
            independence: 4,
            creativity: 3,
            workLifeBalance: -4,
          },
        },
      ],
      explanation: "All nurses make mistakes. Cultures of safety depend on reporting near-misses to prevent future errors. Integrity matters more than perfection.",
      realityNote: "Studies show nurses who report near-misses make fewer serious errors. Safety culture depends on transparency.",
    },
    {
      id: "q7",
      scenario: "You have to perform a painful procedure on a crying child. How do you approach it?",
      options: [
        {
          text: "Just do it quickly to get it over with",
          insight: "Efficient but misses opportunity for trauma-informed care that helps children",
          scores: {
            technical: 6,
            pressure: 6,
            collaboration: 3,
            independence: 7,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Explain at child's level, offer choices where possible, use distraction techniques",
          insight: "Evidence-based pediatric nursing - minimizing trauma while completing necessary care",
          scores: {
            collaboration: 10,
            creativity: 9,
            technical: 9,
            pressure: 8,
            independence: 6,
            workLifeBalance: 4,
          },
        },
        {
          text: "Ask parents to restrain child while I complete procedure",
          insight: "Sometimes necessary but should be last resort after trauma-informed approaches tried",
          scores: {
            technical: 7,
            collaboration: 6,
            pressure: 7,
            independence: 6,
            creativity: 3,
            workLifeBalance: 6,
          },
        },
        {
          text: "Feel distressed by causing the child pain",
          insight: "Compassion is good but nursing requires tolerating causing necessary discomfort",
          scores: {
            pressure: -5,
            collaboration: 6,
            technical: 4,
            independence: 4,
            creativity: 4,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Nurses must perform procedures that cause discomfort. The best do so with minimal trauma using age-appropriate communication and distraction.",
      realityNote: "Pediatric nurses report that trauma-informed techniques reduce procedure time and improve outcomes. Compassion and efficiency aren't opposites.",
    },
  ],
  scoringGuide: {
    technical: { min: -15, max: 70, weight: 0.20 },
    pressure: { min: -35, max: 65, weight: 0.25 },
    collaboration: { min: -25, max: 70, weight: 0.20 },
    creativity: { min: -5, max: 50, weight: 0.10 },
    independence: { min: -10, max: 55, weight: 0.10 },
    workLifeBalance: { min: -30, max: 50, weight: 0.15 },
  },
  results: {
    high: {
      min: 70,
      title: "Nursing is Your Calling",
      message: "Your responses show strong alignment with nursing realities. You demonstrate emotional resilience, patient advocacy, collaboration skills, and the ability to handle pressure while maintaining compassion. You understand the challenges and seem prepared for this demanding but rewarding career.",
    },
    medium: {
      min: 50,
      title: "Nursing Possible With Preparation",
      message: "You have some qualities that align with nursing but may find the emotional intensity, physical demands, or constant pressure challenging. Consider volunteering in healthcare settings or working as a nursing assistant to test your fit before committing to nursing school.",
    },
    low: {
      min: 0,
      title: "Consider Other Healthcare Roles",
      message: "Your responses suggest bedside nursing may not align well with your preferences. However, healthcare offers many paths - consider medical lab work, health informatics, health administration, or allied health professions that leverage your strengths differently.",
    },
  },
};
