/**
 * Sample Reality Quiz for Teacher/Educator Career
 */

export const teacherQuiz = {
  title: "A Day as a Teacher",
  description: "Experience the real challenges and rewards of teaching. See if education is your calling.",
  duration: 7,
  questions: [
    {
      id: "q1",
      scenario: "A student is disrupting class for the third time this week, making it hard for others to learn. How do you handle it?",
      options: [
        {
          text: "Remove them from class immediately and send to principal",
          insight: "You prioritize classroom order but may miss opportunities to address root causes",
          scores: {
            pressure: 5,
            collaboration: -3,
            independence: 7,
            technical: 4,
            creativity: -2,
            workLifeBalance: 6,
          },
        },
        {
          text: "Take them aside privately, understand what's happening, offer support",
          insight: "You show empathy and build relationships - core to effective teaching",
          scores: {
            collaboration: 10,
            pressure: 7,
            creativity: 7,
            independence: 5,
            technical: 8,
            workLifeBalance: 4,
          },
        },
        {
          text: "Ignore it and continue teaching, hoping they'll stop",
          insight: "Avoiding conflict may let issues escalate and hurt learning environment",
          scores: {
            pressure: -5,
            collaboration: -5,
            independence: 3,
            technical: 2,
            creativity: -3,
            workLifeBalance: 5,
          },
        },
        {
          text: "Engage them by making lesson more interactive and relevant to their interests",
          insight: "You adapt teaching to student needs - excellent pedagogical thinking",
          scores: {
            creativity: 10,
            collaboration: 9,
            technical: 9,
            pressure: 7,
            independence: 6,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Effective teachers balance classroom management with understanding individual student needs. The best approach often combines structure with empathy.",
      realityNote: "Teachers deal with behavioral issues almost daily. 73% say classroom management is their biggest ongoing challenge.",
    },
    {
      id: "q2",
      scenario: "You have 40 assignments to grade before tomorrow, and you're exhausted after a full day of teaching. What do you do?",
      options: [
        {
          text: "Push through tonight, stay up late to finish all of them",
          insight: "Strong dedication but this pace leads to burnout without sustainable boundaries",
          scores: {
            pressure: 8,
            technical: 7,
            workLifeBalance: -8,
            independence: 8,
            collaboration: 4,
            creativity: 3,
          },
        },
        {
          text: "Grade a portion tonight, rest, finish tomorrow morning early",
          insight: "You balance responsibility with self-care - key for long-term teaching success",
          scores: {
            pressure: 8,
            workLifeBalance: 7,
            technical: 8,
            independence: 7,
            collaboration: 5,
            creativity: 5,
          },
        },
        {
          text: "Use a rubric to grade faster, prioritize detailed feedback on key assignments only",
          insight: "You work efficiently and strategically - teaching is marathon not sprint",
          scores: {
            creativity: 8,
            technical: 9,
            pressure: 8,
            workLifeBalance: 6,
            independence: 8,
            collaboration: 5,
          },
        },
        {
          text: "Feel overwhelmed and stressed about the workload",
          insight: "Teaching workload is real - need strategies to manage it sustainably",
          scores: {
            pressure: -6,
            workLifeBalance: -4,
            technical: 3,
            independence: 3,
            collaboration: 4,
            creativity: 2,
          },
        },
      ],
      explanation: "Grading is one of the hidden time sinks in teaching. Successful teachers develop efficient systems while maintaining quality feedback.",
      realityNote: "Average teacher works 50-60 hours weekly including grading, planning, and meetings. Work doesn't end when school day does.",
    },
    {
      id: "q3",
      scenario: "A parent emails you aggressively, blaming you for their child's poor grade. How do you respond?",
      options: [
        {
          text: "Defend yourself and explain all the ways the student didn't do the work",
          insight: "While factual, defensive responses escalate conflict rather than resolve it",
          scores: {
            collaboration: -4,
            pressure: 4,
            independence: 6,
            technical: 5,
            creativity: 3,
            workLifeBalance: 5,
          },
        },
        {
          text: "Schedule a meeting to discuss student progress and create support plan together",
          insight: "You turn conflict into partnership - this is professional teaching excellence",
          scores: {
            collaboration: 10,
            pressure: 9,
            technical: 9,
            creativity: 7,
            independence: 6,
            workLifeBalance: 4,
          },
        },
        {
          text: "Forward email to principal and let them handle the angry parent",
          insight: "While sometimes necessary, over-reliance on admin can limit your growth",
          scores: {
            collaboration: 5,
            pressure: 3,
            independence: -3,
            technical: 4,
            creativity: 2,
            workLifeBalance: 7,
          },
        },
        {
          text: "Take it personally and feel anxious about confrontation",
          insight: "Parent conflict is emotionally challenging - resilience is teachable but necessary",
          scores: {
            pressure: -7,
            collaboration: 3,
            workLifeBalance: -5,
            independence: 2,
            technical: 3,
            creativity: 2,
          },
        },
      ],
      explanation: "Parent communication is crucial. The best teachers see parents as partners, even when interactions start contentiously.",
      realityNote: "85% of teachers report difficult parent interactions annually. Learning to navigate these professionally is essential.",
    },
    {
      id: "q4",
      scenario: "Your carefully planned lesson is flopping - students are confused and disengaged. What do you do?",
      options: [
        {
          text: "Stick to the plan - they'll understand eventually",
          insight: "Rigidity can lose students. Teaching requires real-time adaptation",
          scores: {
            creativity: -5,
            collaboration: -2,
            independence: 7,
            technical: 3,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Pause, ask students what's confusing, adjust approach on the fly",
          insight: "You're responsive and student-centered - hallmark of great teaching",
          scores: {
            creativity: 10,
            collaboration: 9,
            technical: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Use a different example or analogy to explain the concept",
          insight: "You think creatively to reach students - excellent pedagogical flexibility",
          scores: {
            creativity: 9,
            technical: 9,
            collaboration: 7,
            pressure: 7,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Feel frustrated that students aren't getting it",
          insight: "Teaching frustration is normal but requires reframing - it's about how you teach it",
          scores: {
            pressure: -4,
            creativity: -3,
            collaboration: 2,
            technical: 4,
            independence: 4,
            workLifeBalance: 3,
          },
        },
      ],
      explanation: "Lessons rarely go exactly as planned. The best teachers read the room and adapt in real-time.",
      realityNote: "Experienced teachers say only 40% of lessons go exactly as planned. The skill is in the adjustment, not the plan.",
    },
    {
      id: "q5",
      scenario: "You're introducing a new curriculum requirement you personally disagree with. How do you handle it?",
      options: [
        {
          text: "Teach it with enthusiasm anyway - it's my job",
          insight: "Professional but may lack authenticity students can sense",
          scores: {
            collaboration: 6,
            pressure: 6,
            independence: 4,
            technical: 7,
            creativity: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Find ways to make it relevant and valuable even if I'm skeptical",
          insight: "You balance professional obligations with creative problem-solving",
          scores: {
            creativity: 9,
            technical: 9,
            collaboration: 7,
            pressure: 7,
            independence: 7,
            workLifeBalance: 5,
          },
        },
        {
          text: "Teach it minimally and focus more on what I think matters",
          insight: "Risky approach that could have professional consequences",
          scores: {
            independence: 8,
            creativity: 6,
            collaboration: -3,
            technical: 5,
            pressure: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Advocate for change through proper channels while teaching it faithfully",
          insight: "You're a professional who engages system improvement - leadership quality",
          scores: {
            collaboration: 10,
            technical: 8,
            independence: 8,
            pressure: 7,
            creativity: 7,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Teachers often implement policies they didn't choose. The best navigate this tension professionally while advocating for students.",
      realityNote: "67% of teachers report teaching content they disagree with. Professional integrity means teaching it well while working to improve the system.",
    },
    {
      id: "q6",
      scenario: "A talented student is underperforming due to difficult home circumstances. What do you do?",
      options: [
        {
          text: "Give them extensions and lower expectations to help them cope",
          insight: "Compassionate but may inadvertently lower expectations that could help them",
          scores: {
            collaboration: 7,
            pressure: 5,
            creativity: 5,
            independence: 5,
            technical: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Connect them with school counselor and social services",
          insight: "You recognize when to involve specialists - professional maturity",
          scores: {
            collaboration: 10,
            technical: 9,
            pressure: 7,
            creativity: 6,
            independence: 6,
            workLifeBalance: 6,
          },
        },
        {
          text: "Maintain high expectations but provide extra support and check-ins",
          insight: "Research shows high expectations + high support = best outcomes for struggling students",
          scores: {
            collaboration: 9,
            technical: 9,
            creativity: 8,
            pressure: 8,
            independence: 7,
            workLifeBalance: 3,
          },
        },
        {
          text: "Feel sad for them but stick to standard requirements",
          insight: "Fair but may miss chance to make real difference in student's life",
          scores: {
            independence: 7,
            technical: 6,
            collaboration: 4,
            pressure: 5,
            creativity: 3,
            workLifeBalance: 7,
          },
        },
      ],
      explanation: "Teaching means meeting students where they are while helping them grow. The best teachers provide both high support and high challenge.",
      realityNote: "Many students face significant challenges outside school. 78% of teachers say addressing student trauma is now part of the job.",
    },
    {
      id: "q7",
      scenario: "Your school wants you to integrate technology you've never used into your lessons. How do you feel?",
      options: [
        {
          text: "Excited to learn new tools and see how they enhance learning",
          insight: "Growth mindset and adaptability - teaching evolves constantly",
          scores: {
            creativity: 10,
            technical: 9,
            pressure: 7,
            collaboration: 7,
            independence: 8,
            workLifeBalance: 4,
          },
        },
        {
          text: "Anxious - I'm comfortable with current methods",
          insight: "Understandable but teaching requires continuous learning as education evolves",
          scores: {
            pressure: -5,
            creativity: -4,
            technical: 2,
            independence: 5,
            collaboration: 4,
            workLifeBalance: 6,
          },
        },
        {
          text: "Ask for training and collaborate with tech-savvy colleagues",
          insight: "You leverage resources and community - smart professional development approach",
          scores: {
            collaboration: 10,
            technical: 8,
            creativity: 7,
            pressure: 7,
            independence: 5,
            workLifeBalance: 6,
          },
        },
        {
          text: "Try it out on my own and experiment with my students",
          insight: "Independent learner willing to take risks - can be powerful or chaotic",
          scores: {
            creativity: 9,
            independence: 10,
            technical: 7,
            pressure: 8,
            collaboration: 4,
            workLifeBalance: 4,
          },
        },
      ],
      explanation: "Education technology changes rapidly. Successful teachers embrace continuous learning while staying focused on pedagogy.",
      realityNote: "Teachers adopt new tools every 2-3 years on average. Those who resist continuous learning struggle as education evolves.",
    },
  ],
  scoringGuide: {
    technical: { min: -10, max: 65, weight: 0.15 },
    pressure: { min: -30, max: 60, weight: 0.20 },
    collaboration: { min: -20, max: 70, weight: 0.25 },
    creativity: { min: -15, max: 70, weight: 0.15 },
    independence: { min: -5, max: 60, weight: 0.10 },
    workLifeBalance: { min: -30, max: 50, weight: 0.15 },
  },
  results: {
    high: {
      min: 70,
      title: "Teaching is Your Calling",
      message: "Your responses show strong alignment with the realities of teaching. You demonstrate empathy, adaptability, collaboration skills, and the resilience needed to thrive in education. You understand it's challenging work but seem prepared to find it rewarding.",
    },
    medium: {
      min: 50,
      title: "Teaching Could Work With Development",
      message: "You have some qualities that align with teaching but may find certain aspects (workload, emotional demands, or constant adaptation) challenging. Consider classroom observation, tutoring, or substitute teaching to test your fit before committing.",
    },
    low: {
      min: 0,
      title: "Consider Alternative Education Roles",
      message: "Your responses suggest traditional classroom teaching may not align well with your preferences. However, education is broad - consider roles in curriculum design, education technology, administration, or corporate training that leverage your strengths differently.",
    },
  },
};
